name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "When I click X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open the application
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Windows Version
      description: What version of Windows are you using?
      placeholder: "Windows 11 23H2"
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: Docker Desktop Version
      description: What version of Docker Desktop are you using?
      placeholder: "Docker Desktop 4.27.0"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Log Files

        **Easiest method:** Click "Report Issue" in the app - it opens the logs folder so you can drag-and-drop files here.

        🔒 **Logs are pre-sanitized** - API keys, passwords, and usernames are automatically redacted, so they're safe to share publicly.

  - type: textarea
    id: logs
    attributes:
      label: Log Files (drag and drop files here)
      description: |
        Drag and drop your log files directly into this box, or paste the contents.

        **Log locations:**
        | Log Type | Location |
        |----------|----------|
        | Windows launcher | `%LOCALAPPDATA%\AI-Docker-CLI\logs\ai-docker.log` |
        | Installation | `<your-workspace>\.ai-docker-cli\logs\install.log` |
        | Container startup | `<your-workspace>\.ai-docker-cli\logs\entrypoint.log` |
        | Updates | `<your-workspace>\.ai-docker-cli\logs\update.log` |
        | Configuration | `<your-workspace>\.ai-docker-cli\logs\configure.log` |
      placeholder: |
        Drag and drop log files here, or paste log contents...

        Example:
        [2026-01-26 14:32:15.123] [INFO] [INSTALL] Installing Claude Code CLI...
        [2026-01-26 14:32:16.456] [ERROR] [INSTALL] npm install failed...
      render: text
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have attached log files or pasted relevant log entries
          required: false
        - label: Docker Desktop is installed and running
          required: false
        - label: I clicked "Report Issue" in the app to access logs easily
          required: false
